function excel_log = readLogExcel(filename)
[~,animallog]=xlsread(filename);
excel_log.AnimalID                      = animallog(2:end,1);
excel_log.Task                          = animallog(2:end,2);
excel_log.TargetPop                     = animallog(2:end,3);
excel_log.Layer                         = animallog(2:end,4);
excel_log.Useful                        = animallog(2:end,5);
excel_log.RFmap                         = animallog(2:end,6);
excel_log.CRF_ORF_before                = animallog(2:end,7);
excel_log.Air_CSplus_CS_minus_unpaired  = animallog(2:end,8);
excel_log.Learning                      = animallog(2:end,9);
excel_log.Learning_plateu               = animallog(2:end,10);
excel_log.CS_shift_learning             = animallog(2:end,11);
excel_log.CS_shift_learning_plateu      = animallog(2:end,12);
excel_log.Psych_test                    = animallog(2:end,13);
excel_log.Psych_test_c50                = animallog(2:end,14);
excel_log.CS_shift_learning             = animallog(2:end,15);
excel_log.extinction                    = animallog(2:end,16);
excel_log.Air_CSpl_CSmin_unpaired_after = animallog(2:end,17);
excel_log.Initial_CSplus                = animallog(2:end,18);
excel_log.Initial_CSminus               =  animallog(2:end,19);
excel_log.Psychtest_full_screen         =  animallog(2:end,20);
excel_log.Psychtest_Saline_and_drug     =  animallog(2:end,21);%(0:nothing; 1:saline; 2:low dose 0.025mg/25g; 3:mid dose 0.05mg/25g; 4:high dose 0.1mg/25g)'
excel_log.RF_map_Drug                   =  animallog(2:end,22);
excel_log.Note                          = animallog(2:end,23);
excel_log.Caframerate                   = animallog(2:end,24);
